language: php

addons:
    code_climate:
        repo_token: 4e7cd8a76f9a996c6e32b2b6f7bca1490f76a0d74b560ec377aeb02143dff2a0

php:
    - 5.6
    - 7.0
    - 7.1

sudo: false

install:
    - composer update
    - travis_retry composer install --no-interaction --prefer-source

before_script: git reset --hard HEAD

script: vendor/bin/phpunit

after_success:
    - vendor/bin/test-reporter
